### ISSUE TITLE
Python 3.7 required to avoid infinite loops when using getNetworkEvents()

### ISSUE THREAD

**Issue by markciecior** [meraki/dashboard-api-python#128]
The logic to stop an infinite loop when pulling network logs depends on the [datetime.fromisoformat()](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) method, which wasn't introduced until python 3.7.  Using this SDK with python 3.6.9 (and earlier versions) can result in an infinite loop; the rest_session instance must hide the exception somewhere.

When running the code manually, I eventually discovered the issue after seeing this error:
_AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'_

[Relevant code here](https://github.com/meraki/dashboard-api-python/blob/51928edb997262708a81b2f60ed5e56097d0ccc6/meraki/rest_session.py#L301)

It appears the [python-dateutil](https://pypi.org/project/python-dateutil/) package offers a solution to this.
[Details here](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse)

**Comment by markciecior** [comment]
Upon further investigation, I was using v1.0.0.  Using v1.4.0, the AttributeError is seen when running getNetworkEvents().

**Comment by TKIPisalegacycipher** [comment]
Hi @markciecior and thanks for reporting this. The setup guide does mention using the most recent version of Python, which at this point is 3.9.0--but as you mentioned, this works on 3.7 as well. Seems like 3.7 is the soft requirement.

I will close this for now, but as always, we welcome outside pull requests should you like to help improve the SDK!
