### ISSUE TITLE
nac category is not working in the 4.4.0b0 release

### ISSUE THREAD

**Issue by abrokas** [meraki/dashboard-api-python#472]
**Describe how you confirmed the issue is with the library, and not with the API itself, or a server-side issue of some other kind.**
I tried to use the "nac" category endpoints from the early access API such as https://developer.cisco.com/meraki/api-v1/get-organization-nac-license-usage/, but nac is not available as a category in the DashboardAPI() instance.

**Python version installed**
3.14

**Meraki library version installed**
4.4.0b0

**Have you reproduced the issue with the latest version of this library? And with the latest version of Python?**
Yes

**OS Platform**
Linux

**Describe the bug**
The "nac" category is not available to use, but the calls seem to be defined under the api folder. An import of the Nac class is missing in the main init file.

**How can we replicate the problem you're reporting?**

This operation should work for example:
```
>>> import meraki
>>> db = meraki.DashboardAPI(api_key)
>>> db.nac.getOrganizationNacLicenseUsage(orgid)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    db.nac.getOrganizationNacLicenseUsage(orgid)
    ^^^^^^
AttributeError: 'DashboardAPI' object has no attribute 'nac'
```

**Expected behavior**
The nac category should be available.

**Code snippets**
See example above
